version: '3.8'

services:
  product_service:
    build: ./product_service
    ports:
      - "5001:5001"

  inventory_service:
    build: ./inventory_service
    ports:
      - "5003:5003"

  customer_service:
    build: ./customer_service
    ports:
      - "5002:5002"
    depends_on:
      - inventory_service
      - product_service

  order_service:
    build: ./order_service
    ports:
      - "5004:5004"

  delivery_service:
    build: ./delivery_service
    ports:
      - "5005:5005"

  analytics_service:
    build: ./analytics_service
    ports:
      - "5006:5006"

  frontend:
    build: ./frontendnya
    ports:
      - "3000:3000"
