version: '3.8'

services:
  order-service:
    image: comiscs/tubes_eai:order_service
    build: .
    ports:
      - "5004:5004"
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=
      - MYSQL_DATABASE=order_db
    volumes:
      - ./data:/app/data
    depends_on:
      - mysql
    networks:
      - bookstore-network

  mysql:
    image: mysql:8.0
    ports:
      - "3308:3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=order_db
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - bookstore-network

volumes:
  mysql-data:

networks:
  bookstore-network:
    name: bookstore-network 