version: '3.8'

services:
  order-service:
    image: comiscs/tubes_eai:order_service
    build: .
    ports:
      - "5004:5004"
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=order_password
      - MYSQL_DATABASE=order_db
      - CUSTOMER_SERVICE_URL=http://host.docker.internal:5000
      - PRODUCT_SERVICE_URL=http://host.docker.internal:5002
    volumes:
      - ./data:/app/data
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - bookstore-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

  mysql:
    image: mysql:8.0
    ports:
      - "3308:3306"  # Exposed for external access (analytics service)
    environment:
      - MYSQL_ROOT_PASSWORD=order_password
      - MYSQL_DATABASE=order_db
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-porder_password"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - bookstore-network

volumes:
  mysql-data:

networks:
  bookstore-network:
    name: bookstore-network
    # This network allows other services to connect to the MySQL database
    # Analytics service can connect using:
    # - Host: localhost (if running on host) or container name (if in same network)
    # - Port: 3308 (external) or 3306 (internal)
    # - User: root
    # - Password: order_password
    # - Database: order_db 